router:
  preferred: '*dalet, 97.107.133.86 8787'
  list:
  - '*dalet, 97.107.133.86 8787'
  password: 0
  mudlistID: 0
autoConnect: false
adminEmail: 'your@email.address.here'
hostName: 'minecraft.hostname.here:25565'
debug: false
