# Plugin meta-data.
name: Intermud3
main: uk.org.rockthehalo.intermud3.Intermud3
version: 1.0
description: Intermud3 client for Bukkit servers.
author: Tricky1702

# Intermud3 commands.
commands:
  intermud3:
    aliases: [ i3 ]
    description: A bridge connecting Minecraft to Intermud3
    usage: |
        /<command> connect - connect to the preferred router.
        /<command> disconnect - disconnect from the router.
        /<command> msg <channel> <message> - sends a message to the specified Intermud3 channel.
        /<command> emote <channel> <emote> - sends an emote to the specified Intermud3 channel.

# Intermud3 permissions.        
permissions:
  intermud3.*:
    default: op
    description: Allows the use of all /intermud3 commands.
    children:
      intermud3.connect: true
      intermud3.disconnect: true
      intermud3.msg: true
      intermud3.emote: true
  intermud3.connect:
    description: Allows the use of /intermud3 connect.
  intermud3.disconnect:
    description: Allows the use of /intermud3 disconnect.
  intermud3.msg:
    description: Allows the use of /intermud3 msg.
  intermud3.emote:
    description: Allows the use of /intermud3 emote.
